# Copyright (C) 2014  Intel Corporation

# Intel C2000 ONIE installer configuration

description="X86_64"
found_ata_device=false

# Default ONIE block device
install_device_platform()
{
    for dir in /sys/block/*/device/; do
       [ -r "${dir}/vendor" ] && \
       [ "$(cat ${dir}/vendor | tr " " "_")" = "ATA_____" ] && {
          echo $dir | sed -e 's#^/sys/block/\(.*\)/device/$#/dev/\1#'
          found_ata_device=true
          break;
       }
    done

    if [ "$found_ata_device" = false ]; then
       echo "/dev/mmcblk0"
    fi
}

# Local Variables:
# mode: shell-script
# eval: (sh-set-shell "/bin/sh" t nil)
# End:
